### ISSUE TITLE
what about joining efforts

### ISSUE THREAD

**Issue by andrzejsliwa** [unbalancedparentheses/spawnedshelter#24]
Hi Guys, really nice page, but what about merging links base from
 
https://github.com/0xAX/erlang-bookmarks/blob/master/ErlangBookmarks.md

there is already lots of contributions.

**Comment by unbalancedparentheses** [comment]
@andrzejsliwa thanks! 

Before creating Spawned Shelter, I was already aware of https://github.com/0xAX/erlang-bookmarks and https://github.com/drobakowski/awesome-erlang. Those repositories are great. 

I decided to create Spawned Shelter because those repositories are a big indexes of libraries, books and posts. Our objective was, and still is, to select only a small subset consisting of the best posts, books, talks for learning Erlang. It is a way to reduce the signal-noise ratio for beginners. 

I will add in other resources section a link to erlang bookmarks and to awesome erlang.
