### ISSUE TITLE
CSS link style problem (UX related)

### ISSUE THREAD

**Issue by kvakvs** [unbalancedparentheses/spawnedshelter#8]
Links are indistinguishable from normal text.

This should be fixed, make them stand out or be underlined, or thick underlined (border-bottom).

Making this an issue and not PR because it should be discussed first i guess?

**Comment by unbalancedparentheses** [comment]
@kvakvs I don't want to add the underlined or a bottom border because it doesn't suit very well the design of the web page. But I think I will make the link turn into another color when you hover it. I will check other websites to see how they stand out links without underlining them. If you have any idea, please let me know.

Thanks for the comment :).

**Comment by unbalancedparentheses** [comment]
On hover the links change the color :)

**Comment by kvakvs** [comment]
On dark-red background link hover color matches the background. Should give them another class, or i possibly could fix that in a PR, if noone else fixes.

**Comment by unbalancedparentheses** [comment]
@kvakvs done.
